repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        description: Checks for correct formatting on all staged frontend files
        stages: [commit]
        types: [file]
        files: \.(js|jsx)$
        entry: prettier --write

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        description: Checks for correct linting on all staged frontend files
        stages: [commit]
        types: [file]
        files: \.(json|js|jsx)$
        additional_dependencies:
          - eslint@8.57.0
          - eslint-config-react-app@7.0.1
          - "@babel/eslint-parser@7.23.10"
          - "@babel/preset-env"
          - "@babel/plugin-proposal-private-property-in-object"
          - eslint-plugin-simple-import-sort@8.0.0
          - eslint-plugin-unused-imports@2.0.0
          - eslint-plugin-json-format@2.0.1
        args: ["--fix"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--allow-multiple-documents", "--unsafe"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
