# Use an official Python runtime as a base image
FROM python:3.9.19 as base

LABEL Author="Yukio Fukuzawa"

ENV PYTHONUNBUFFERED 1

ARG uid=1000

ARG http_proxy=''
ARG https_proxy=''
ENV http_proxy=''
ENV https_proxy=''
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# Install extra packages.
RUN apt update && apt-get install -y --no-install-recommends vim mariadb-client ffmpeg libxml2-dev libxmlsec1-dev gfortran #&& rm -rf /var/lib/apt/lists/*
RUN apt install -y build-essential
RUN rm -rf /var/lib/apt/lists/*

COPY pyproject.toml /

## Install any needed packages specified in requirements.txt
RUN python3 -m pip install --upgrade pip
RUN pip3 uninstall -y numpy scipy


# Install Poetry
COPY poetry-install.py /
RUN python3 poetry-install.py
ENV PATH="/root/.local/bin:${PATH}"

COPY pyproject.toml poetry.lock /

# Install dependencies using Poetry
RUN poetry config virtualenvs.create false && poetry install --without dev

COPY requirements-production.txt /
RUN pip3 install -r requirements-production.txt --no-cache-dir

# Make port 8000 available to the world outside this container
EXPOSE 8000

WORKDIR /code

COPY . .

ENTRYPOINT ["/bin/bash"]
CMD ["run_koe_app.sh"]
