# Exclude a variety of commonly ignored directories.
exclude = [
    ".venv",
    "node_modules",
    "migrations",
    "__init__.py",
    "**/management/commands/_*.py",
    "jupyter_notebook_config.py",
    "notebooks/,_*.py",
    ".git",
    "__pycache__",
    "static",
]

# Same as Black.
line-length = 119
indent-width = 4

# Assume Python 3.8
target-version = "py39"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E4", "E7", "E9", "F"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
