# Generated by Django 2.0.1 on 2018-02-10 04:45

from django.db import migrations, models
import django.db.models.deletion
import root.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('fs', models.IntegerField()),
                ('length', models.IntegerField()),
                ('name', models.CharField(max_length=1024)),
                ('quality', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, root.models.AutoSetterGetterMixin),
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, root.models.AutoSetterGetterMixin),
        ),
        migrations.CreateModel(
            name='CompareAlgorithm',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, root.models.AutoSetterGetterMixin),
        ),
        migrations.CreateModel(
            name='DistanceMatrix',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('chksum', models.CharField(max_length=24)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koe.CompareAlgorithm')),
            ],
            bases=(models.Model, root.models.AutoSetterGetterMixin),
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, root.models.AutoSetterGetterMixin),
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_ms', models.IntegerField()),
                ('end_time_ms', models.IntegerField()),
            ],
            options={
                'ordering': ('segmentation', 'start_time_ms'),
            },
            bases=(models.Model, root.models.AutoSetterGetterMixin),
        ),
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=1023)),
                ('audio_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koe.AudioFile')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, root.models.AutoSetterGetterMixin),
        ),
        migrations.CreateModel(
            name='ValueForSorting',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koe.CompareAlgorithm')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koe.Segment')),
            ],
            bases=(models.Model, root.models.AutoSetterGetterMixin),
        ),
        migrations.AddField(
            model_name='segment',
            name='segmentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koe.Segmentation'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='koe.Individual'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='koe.AudioTrack'),
        ),
        migrations.AlterUniqueTogether(
            name='valueforsorting',
            unique_together={('segment', 'algorithm')},
        ),
        migrations.AlterUniqueTogether(
            name='distancematrix',
            unique_together={('chksum', 'algorithm')},
        ),
    ]
