# Generated by Django 2.0.1 on 2018-02-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0002_historyentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
