# Generated by Django 2.0.4 on 2018-08-16 09:05

from django.db import migrations, models
import root.models


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0003_segment_tid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, root.models.AutoSetterGetterMixin),
        ),
    ]
