# Generated by Django 2.0.1 on 2018-02-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0003_auto_20180212_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='mean_ff',
            field=models.FloatField(null=True),
        ),
    ]
