# Generated by Django 2.0.1 on 2018-02-17 02:49

from django.db import migrations, models
import root.models


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0005_auto_20180215_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('algorithm', models.CharField(max_length=255)),
                ('chksum', models.CharField(max_length=24)),
            ],
            bases=(root.models.AutoSetterGetterMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='valueforsorting',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='valueforsorting',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='valueforsorting',
            name='segment',
        ),
        migrations.AlterField(
            model_name='distancematrix',
            name='algorithm',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CompareAlgorithm',
        ),
        migrations.DeleteModel(
            name='ValueForSorting',
        ),
        migrations.AlterUniqueTogether(
            name='coordinate',
            unique_together={('chksum', 'algorithm')},
        ),
    ]
