# Generated by Django 2.0.4 on 2018-09-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0005_auto_20180820_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='tid',
            field=models.IntegerField(null=True),
        ),
    ]
