# Generated by Django 2.0.1 on 2018-03-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0007_database_databaseassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='database',
            field=models.ForeignKey(default='de1', on_delete=django.db.models.deletion.CASCADE, to='koe.Database'),
            preserve_default=False,
        ),
    ]
