# Generated by Django 2.0.1 on 2018-03-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0009_auto_20180314_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='database',
            field=models.ForeignKey(default='de1', on_delete=django.db.models.deletion.CASCADE, to='koe.Database'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distancematrix',
            name='database',
            field=models.ForeignKey(default='de1', on_delete=django.db.models.deletion.CASCADE, to='koe.Database'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='coordinate',
            unique_together={('chksum', 'algorithm', 'database')},
        ),
        migrations.AlterUniqueTogether(
            name='distancematrix',
            unique_together={('chksum', 'algorithm', 'database')},
        ),
    ]
