# Generated by Django 2.0.4 on 2018-10-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0010_temporarydatabase__databases'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='started',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
