# Generated by Django 2.0.1 on 2018-05-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0011_auto_20180503_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyentry',
            options={'ordering': ['-time', 'user']},
        ),
    ]
