# Generated by Django 2.0.1 on 2018-05-11 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0013_auto_20180511_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='koe.AudioFile'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='audiofile',
            unique_together={('name', 'database')},
        ),
    ]
