# Generated by Django 2.0.1 on 2018-05-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0014_auto_20180511_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='permission',
            field=models.IntegerField(choices=[(1, 'View'), (2, 'Annotate'), (3, 'Copy Files'), (4, 'Add Files'), (5, 'Delete Files'), (10, 'Assign User')], default=1),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='koe.AudioFile'),
        ),
        migrations.AlterField(
            model_name='databaseassignment',
            name='permission',
            field=models.IntegerField(choices=[(1, 'View'), (2, 'Annotate'), (3, 'Copy Files'), (4, 'Add Files'), (5, 'Delete Files'), (10, 'Assign User')]),
        ),
    ]
