# Generated by Django 2.0.1 on 2018-05-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0015_auto_20180511_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='permission',
            field=models.IntegerField(choices=[(1, 'View'), (2, 'Annotate'), (3, 'Copy Files'), (4, 'Add Files'), (5, 'Modify Segments'), (6, 'Delete Files'), (10, 'Assign User')], default=1),
        ),
        migrations.AlterField(
            model_name='databaseassignment',
            name='permission',
            field=models.IntegerField(choices=[(1, 'View'), (2, 'Annotate'), (3, 'Copy Files'), (4, 'Add Files'), (5, 'Modify Segments'), (6, 'Delete Files'), (10, 'Assign User')]),
        ),
    ]
