# Generated by Django 2.0.1 on 2018-05-16 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0016_auto_20180512_0318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyentry',
            options={'ordering': ['-time', 'user', 'database']},
        ),
        migrations.AddField(
            model_name='historyentry',
            name='database',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='koe.Database'),
        ),
        migrations.AddField(
            model_name='historyentry',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historyentry',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='permission',
            field=models.IntegerField(choices=[(100, 'View'), (200, 'Annotate'), (300, 'Import Data'), (400, 'Copy Files'), (500, 'Add Files'), (600, 'Modify Segments'), (700, 'Delete Files'), (800, 'Assign User')], default=100),
        ),
        migrations.AlterField(
            model_name='databaseassignment',
            name='permission',
            field=models.IntegerField(choices=[(100, 'View'), (200, 'Annotate'), (300, 'Import Data'), (400, 'Copy Files'), (500, 'Add Files'), (600, 'Modify Segments'), (700, 'Delete Files'), (800, 'Assign User')]),
        ),
    ]
