# Generated by Django 2.0.1 on 2018-05-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0017_auto_20180516_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyentry',
            name='type',
            field=models.CharField(default='labels', max_length=32),
        ),
    ]
