# Generated by Django 2.0.4 on 2018-05-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0018_historyentry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='quality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
