# Generated by Django 2.0.4 on 2019-05-09 01:41

from django.db import migrations, models
import django.db.models.deletion
import root.models


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0019_move_audio_files_to_database_folders'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('permission', models.IntegerField(choices=[(100, 'View'), (200, 'Annotate'), (300, 'Import Data'), (400, 'Copy Files'), (450, 'Download Files'), (500, 'Add Files'), (600, 'Modify Segments'), (700, 'Delete Files'), (800, 'Assign User')])),
                ('expiry', models.DateTimeField()),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koe.Database')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, root.models.AutoSetterGetterMixin),
        ),
        migrations.AddField(
            model_name='databaseassignment',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
