# Generated by Django 2.0.4 on 2019-07-08 12:18

from django.db import migrations, models


def change_genus_species_to_name(apps, schema_editor):
    """
    Up to now the spects are
    """
    db_alias = schema_editor.connection.alias
    species = apps.get_model('koe', 'Species')
    for species_item in species.objects.using(db_alias).all():
        species_item.name = species_item.genus + " " + species_item.species
        species_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0020_auto_20190509_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RunPython(change_genus_species_to_name),
        migrations.AlterUniqueTogether(
            name='species',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='species',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='species',
            name='species',
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
