# Generated by Django 2.0.4 on 2019-10-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("koe", "0023_merginginfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="fake_fs",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
