# Generated by Django 2.0.4 on 2019-12-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("koe", "0025_auto_20191201_0702"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
