# Generated by Django 2.0.4 on 2019-12-16 23:09

from django.db import migrations, models
import django.db.models.deletion
import root.models


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0028_audiofile_num_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='RnnSegmentor',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('input_dim', models.IntegerField()),
                ('window_len', models.IntegerField()),
                ('nfft', models.IntegerField()),
                ('noverlap', models.IntegerField()),
                ('model_path', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('format', models.CharField(max_length=255)),
                ('database', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='koe.Database')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, root.models.AutoSetterGetterMixin),
        ),
    ]
