# Generated by Django 2.0.4 on 2020-05-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("koe", "0033_add_name_to_species"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="end_time_ms",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="segment",
            name="start_time_ms",
            field=models.FloatField(),
        ),
    ]
