# Generated by Django 2.0.4 on 2021-10-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koe', '0029_rnnsegmentor'),
        ('koe', '0036_auto_20200524_2123'),
    ]

    operations = [
    ]
