# Generated by Django 2.0.1 on 2018-02-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extraattrvalue',
            unique_together={('user', 'owner_id', 'attr')},
        ),
    ]
