# Generated by Django 2.0.1 on 2018-02-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20180211_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnactionvalue',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='columnactionvalue',
            name='column',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='columnactionvalue',
            name='table',
            field=models.CharField(max_length=255),
        ),
    ]
