# Generated by Django 2.0.1 on 2018-03-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20180212_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraattrvalue',
            options={'ordering': ('user', 'attr', 'owner_id')},
        ),
    ]
