# Generated by Django 2.0.1 on 2018-03-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_auto_20180314_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraattrvalue',
            options={},
        ),
    ]
